# Generated by Django 4.0.5 on 2022-07-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
